var vocabular;


String serverURL = 'https://permit.matfmc.ru/';//${serverURL}

var s1 = vocabular['forms']['forms_n']; //используется
//var s2 = '5 записей';//??
var s3 = vocabular['registry']['status_panel']['select']; //используется
var s4 = vocabular['forms']['all_forms']; //Используется
var s5 = vocabular['registry']['datepicker_filters']['today'];//??
//var s6 = 'UUEE → UUAS';//??
//var s7 = '14.05.2020 в 19:40, WWW00002,  Авиакомпания «Сибирь»';//??
var s8 = vocabular['registry']['top_filters']['processing'];//Используется
//var s9 = '14.05.2020';//??
var s10 = 'отказа: «Отсутствует разрешение ФСБ»';//??
var s11 = vocabular['forms']['create']; // используется
var s12 = vocabular['registry']['status_panel']['configure_access'];// используется
var s13 = vocabular['registry']['status_panel']['archive'];// используется
var s14 = vocabular['registry']['status_panel']['export'];// используется
var s15 = vocabular['registry']['status_panel']['duplicate'];// используется
//var s16 = 'Выбрать';// используется
var s17 = vocabular['myPhrases']['addFavorite'];// используется
var s18 = vocabular['myPhrases']['formInfo'];// используется
var s19 = vocabular['registry']['status_panel']['to_approve'];// используется
var s20 = vocabular['registry']['status_panel']['postpone'];// используется
var s21 = vocabular['registry']['status_panel']['reject'];// используется
var s22 = 'Согласовать  «Нерегулярный рейс №125»';
var s23 = vocabular['myPhrases']['flightDetails'];
var s24 = 'Авиапредприятие (OPR/)';
var s25 = 'Swiss International Air Lines Ltd';
var s26 = vocabular['registry']['manage_table_fields']['from_where'];
var s27 = 'Цюрих (Клотен)';
var s28 = 'LSZH';
var s29 = vocabular['registry']['manage_table_fields']['where'];
var s30 = 'Ханчжоу (Сяошань)';
var s31 = 'ZSHC';
var s32 = vocabular['registry']['flight_number'];
var s33 = 'SBI847';
var s34 = vocabular['myPhrases']['regNumPlane'];
var s35 = 'RA10254';
var s36 = vocabular['myPhrases']['dateOut'];
var s37 = '14.04.2020';//??
var s38 = vocabular['myPhrases']['dateIn'];
var s39 = '15.04.2020';//??
var s40 = vocabular['form_n']['purpose_flight'];
var s41 = vocabular['form_n']['purposeFlight']['none_commercial_flight'];
var s42 = vocabular['myPhrases']['transferCategory'];
var s43 = 'Чартерный пассажирский';
var s44 = vocabular['myPhrases']['containedFiles'];
var s45 = 'Разрешение ФСБ';
var s46 = 'согласование Участков маршрута';
var s47 = vocabular['myPhrases']['fligh'];//Используется
var s48 = vocabular['myPhrases']['landing'];//Используется
var s49 = 'Согласовать выбранные участки';
var s50 = 'Отложить  «Нерегулярный рейс №125»';
//var s51 = 'Отложить';//Используется
var s52 = vocabular['myPhrases']['cause'];//Используется
var s53 = 'Нерегулярный рейс'; //Используется
var s54 = vocabular['form_n']['flight_information']; //Используется
var s55 = vocabular['registry']['statement'];
var s56 = '1. B Код ИКАО авиапредприятия *_1';
var s57 = '1. C Страна регистрации *_1';
var s58 = '2. Опознавательный индекс ВС (номер...';
var s59 = vocabular['header']['aircrafts'];
var s60 = '3. А Тип основного ВС *';
var s61 = '3.B Регистр. номер ВС *_1';
var s62 = '3. C Макс. взлетная масса *';
var s63 = '3. C Макс. посад. масса *';
var s64 = '3. D Вес пустого снаряж.';
var s65 = '4 – владелец ВС';
var s66 = '4. A Владелец ВС *_4';
var s67 = '4. B Контактные данные владельца *';
var s68 = '4. B Адрес владельца ВС (Государство и полный адрес) *_1';
var s69 = '5 – цель выполнения перевозки';
var s70 = '6. Категория перевозки *';
var s71 = 'Чартерный пассажирский';
var s72 = 'Коммерческий рейс';
var s73 = '7 – экипаж';
var s74 = '7. ФИО *';
var s75 = '7. Гражданство *';
var s76 = vocabular['form_n']['crew']['add_crew_member'];
var s77 = '8 – пассажиры';
var s78 = 'Фрахтователь (наименование) *';
var s79 = 'Полный адрес и контакты *';
var s80 = 'Принимающая сторона (наименование) *';
var s81 = 'Полный адрес и контакты *';
//var s82 = '9 – маршрут';
var s83 = '9. Дата отправления *_6';
var s84 = '9. Аэропорт отправления *_5';
var s85 = vocabular['registry']['flight_num'];
//var s86 = '9. Время вылета *';
var s87 = '9. Точка входа в ВП РФ *';
var s88 = '9. Время входа *';
var s89 = '9. Точка выхода из ВП РФ *';
var s90 = '9. Время выхода *';
var s91 = '9. Дата прибытия *_6';
var s92 = '9. Аэропорт назначения *_5';
//var s93 = '9. Номер рейса *';
var s94 = vocabular['registry']['boarding_time'];
var s95 = 'Пролет над РФ';
var s96 = 'Посадка в РФ';
var s97 = '10 – Форма оплаты услуг и государственных  сборов';
var s98 = '10. Адрес плательщика *';
var s99 = '10. Банк *';
var s100 = '10. Номер счета *';
var s101 = 'Примечание_1';
//var s102 = 'прикрепленные файлы';
var s103 = vocabular['form_n']['general']['attach_files'];
var s104 = vocabular['forms']['send'];
var s105 = 'Регулярный рейс';
var s106 = vocabular['form_n']['flight_information'];
var s107 = 'Полное наименование авиапредприятия (OPR/) *';
var s108 = 'Номер рейса *';
var s109 = 'SWR (LX) 2688_1';
var s110 = 'Дата c *';
var s111 = 'Дата до *';
var s112 = vocabular['registry']['flight_days'];
var s113 = vocabular['registry']['road'];
var s114 = vocabular['myPhrases']['airportFlight'];
var s115 = vocabular['myPhrases']['airportLanding'];
var s116 = vocabular['registry']['departure_time'];
//var s117 = 'Время посадки *';
var s118 = 'Добавить пункты Stop-over';
var s119 = 'Добавить пункты технических посадок';
var s120 = 'Добавить участки с коммерческими правами';
var s121 = vocabular['form_r']['aircraft'];
var s122 = 'Тип основного ВС *_5';
var s123 = 'Компоновка основного ВС *_1';
var s124 = 'Добавить запасное ВС';
var s125 = vocabular['form_r']['entry_exit_points'];
var s126 = 'Точка входа в ВП РФ *_2';
var s127 = 'Точка выхода в ВП РФ *_2';
var s128 = 'Время входа *_7';
var s129 = 'Время выхода *_7';
var s130 = 'Запасные точки входа в ВП РФ *_2';
var s131 = 'Запасные точки выхода из ВП РФ *_2';
var s132 = 'Примечание_1';
var s133 = 'прикрепленные документы';
var s134 = vocabular['form_r']['general']['attach_files'];
var s136 = 'Пункты посадки с правом «Stop-over»';
var s137 = 'Пункт «Stop-over»_5';
//var s138 = 'Время вылета *';
//var s139 = 'Время посадки *';
var s140 = 'Пункты технических посадок';
var s141 = 'Пункт технической посадки_5';
//var s142 = 'Время вылета *';
//var s143 = 'Время посадки *';
var s144 = 'Участки с коммерческими правами';
var s145 = 'Причина отказа *';
var s146 = 'Разрешение ФСБ';
//var s147 = 'Согласовать';
var s148 = vocabular['form_r']['general']['forms_r'];//Используется
var s149 = 'Действителен с';
var s150 = 'Действителен до';
var s151 = 'Дни выполнения';
//var s152 = '14.04.2020';//??
var s153 = '27.04.2020';
var s154 = vocabular['myPhrases']['filters'];
var s155 = vocabular['myPhrases']['newFilter'];
var s156 = vocabular['forms']['my_filters'];
var s157 = vocabular['myPhrases']['sortWith'];
var s158 = vocabular['myPhrases']['flightDateTime'];
var s159 = vocabular['myPhrases']['showArh'];
var s160 = vocabular['myPhrases']['messageType'];
var s161 = vocabular['registry']['manage_table_fields']['from_where'];
var s162 = vocabular['myPhrases']['flightDateTime'];
var s163 = '00.00.0000 в 00:00';
var s164 = 'Плановое скоррект. время вылета';
var s165 = vocabular['registry']['manage_table_fields']['where'];
var s166 = 'КВС';
var s167 = 'SID';
var s168 = vocabular['myPhrases']['factFlightDateTime'];
var s169 = vocabular['myPhrases']['apply'];
var s170 = vocabular['registry']['user_profile']['back']; //Используется
var s171 = 'Внуково';
var s172 = 'UUWW';
var s173 = vocabular['registry']['status_panel']['select'];
var s174 = 'Свернуть все'; //Используется
//примерно тут начал Колдашев Д.Ю.
var s175 = vocabular['myPhrases']['appName'];
var s176 = vocabular['auth']['login'];
//var s177 = 'Пароль *';
var s178 = vocabular['auth']['password']['confirmation'];
var s179 = vocabular['auth']['register_page']['surname'];
var s180 = vocabular['auth']['register_page']['name'];
var s181 = vocabular['auth']['register_page']['lastname'];
var s182 = vocabular['myPhrases']['acceptRules'];
//var s183 = 'Войти';
var s184 = vocabular['auth']['login_page']['restore_access'];
//var s185 = 'Информация о ';
//var s186 = 'Пользовательском соглашении';
var s187 = vocabular['auth']['register'];
var s188 = vocabular['myPhrases']['accept'];
var s189 = vocabular['auth']['register_page']['phone'];
var s190 = vocabular['myPhrases']['ICAOcode'];
var s191 = vocabular['header']['settings'];
//var s192 = 'Запросы';
String headerValue = s250;
var s193 = vocabular['header']['exit'];
var s194 = vocabular['header']['groups'];
var s195 = vocabular['myPhrases']['users'];
var s196 = vocabular['myPhrases']['userPoints'];
var s197 = vocabular['myPhrases']['myTemplates'];
var s198 = vocabular['myPhrases']['appSettings'];
var s199 = vocabular['header']['help'];
var s200 = vocabular['myPhrases']['about'];
var s201 = vocabular['notification']['delete_everything'];
var s202 = vocabular['myPhrases']['openReceipt'];
var s203 = vocabular['myPhrases']['notification'];
var s204 = vocabular['header']['profile_and_settings'];
var s205 = vocabular['header']['profile'];
var s206 = vocabular['header']['roles'];
var s207 = vocabular['registry']['user_profile']['personal_data'];
var s208 = vocabular['registry']['user_profile']['update_data'];
var s209 = vocabular['myPhrases']['changingPassword'];
var s210 = vocabular['myPhrases']['passNoCompare'];
var s211 = vocabular['myPhrases']['changePassword'];
var s212 = vocabular['myPhrases']['exit'];
var s213 = vocabular['myPhrases']['moreInfo'];
var s214 = vocabular['myPhrases']['general'];
var s215 = vocabular['myPhrases']['language'];
var s216 = 'Доступ по телефону';
var s217 = vocabular['myPhrases']['other'];
var s218 = 'Единицы измерения';
var s219 = 'Единицы измерения температуры';
var s220 = 'Единицы измерения давления';
var s221 = 'Единицы измерения стоимости топлива';
var s222 = 'Единицы измерения вертик. скор. полета';
var s223 = 'Единицы измерения гориз. скор. полета';
var s224 = 'Формат даты';
var s225 = 'Отображение координат';
var s226 = 'Единицы измерения расстояния';
var s227 = 'Единицы измерения высоты';
var s228 = vocabular['myPhrases']['routTimeOutType'];
var s229 = 'Сгенер. список однораз. паролей';
var s230 = 'Исп. одноразовые пароли';
var s231 = vocabular['myPhrases']['showUTC'];
var s232 = 'Доступ для Нафани';
var s233 = 'Мин. высота';
var s234 = 'Макс. высота';
var s235 = 'Автороутинг';
var s236 = 'Настроить уведомления';
var s237 = 'Перейти к подключению SMS';
var s238 = 'Код отправки';
var s239 = 'Идентификатор отправки';
var s240 = 'SMS-уведомления';
var s241 = vocabular['myPhrases']['emailNotif'];
var s242 = vocabular['myPhrases']['themeType'];
var s243 = vocabular['registry']['user_role']['pilot'];
var s244 = vocabular['registry']['user_role']['tune'];
var s245 = 'Внешний пилот БВС';
var s246 = 'Эксплуатант';
var s247 = 'Доверенные пользователи';
var s248 = 'Ожидание запроса';
var s249 = vocabular['myPhrases']['addUser'];
var s250 = vocabular['myPhrases']['reestr'];
var s251 = vocabular['header']['forms_r/n'];
var s252 = vocabular['forms']['form'];
var s253 = vocabular['history'];
var s254 = "${vocabular['form_n']['aircraft'][0].toUpperCase()}${vocabular['form_n']['aircraft'].substring(1)}";//aircraft
var s255 = "${vocabular['form_n']['aircraft_reserve'][0].toUpperCase()}${vocabular['form_n']['aircraft_reserve'].substring(1)}";//"${vocabular['form_n']['aircraft_reserve'][0].toUpperCase()}${vocabular['form_n']['aircraft_reserve'].substring(1)}"
var s256 = "${vocabular['form_n']['main_departure_date'][0].toUpperCase()}${vocabular['form_n']['main_departure_date'].substring(1)}";//main_departure_date
var s257 = vocabular['form_n']['main_departure_date_obj']['repetitions'];
var s258 = vocabular['form_n']['flight_crew'];
var s259 = vocabular['form_n']['cargo'];
var s260 = vocabular['myPhrases']['payer'];
//var s260 = 'ЛИЦО ОПЛАЧИВАЮЩЕЕ АЭРОНАВИГАЦИОННЫЕ СБОРЫ';
var s261 = "${vocabular['form_n']['comment'][0].toUpperCase()}${vocabular['form_n']['comment'].substring(1)}";//"${vocabular['form_n']['comment'][0].toUpperCase()}${vocabular['form_n']['comment'].substring(1)}"
var s262 = vocabular['myPhrases']['hintAviacompanyNameOrICAO'];
var s263 = vocabular['myPhrases']['stateOfRegistry'];
var s264 = vocabular['form_n']['general']['add_document'];
var s265 = vocabular['myPhrases']['notes'];

reloadLanguage(){
  s1 = vocabular['forms']['forms_n']; //используется
// s2 = '5 записей';//??
  s3 = vocabular['registry']['status_panel']['select']; //используется
  s4 = vocabular['forms']['all_forms']; //Используется
  s5 = vocabular['registry']['datepicker_filters']['today'];//??
// s6 = 'UUEE → UUAS';//??
// s7 = '14.05.2020 в 19:40, WWW00002,
  //Авиакомпания «Сибирь»';//??
  s8 = vocabular['registry']['top_filters']['processing'];//Используется
// s9 = '14.05.2020';//??
  s10 = 'отказа: «Отсутствует разрешение ФСБ»';//??
  s11 = vocabular['forms']['create']; // используется
  s12 = vocabular['registry']['status_panel']['configure_access'];// используется
  s13 = vocabular['registry']['status_panel']['archive'];// используется
  s14 = vocabular['registry']['status_panel']['export'];// используется
  s15 = vocabular['registry']['status_panel']['duplicate'];// используется
// s16 = 'Выбрать';// используется
  s17 = vocabular['myPhrases']['addFavorite'];// используется
  s18 = vocabular['myPhrases']['formInfo'];// используется
  s19 = vocabular['registry']['status_panel']['to_approve'];// используется
  s20 = vocabular['registry']['status_panel']['postpone'];// используется
  s21 = vocabular['registry']['status_panel']['reject'];// используется
  s22 = 'Согласовать';
  //«Нерегулярный рейс №125»';
  s23 = vocabular['myPhrases']['flightDetails'];
  s24 = 'Авиапредприятие (OPR/)';
  s25 = 'Swiss International';
  //Air Lines Ltd';
  s26 = vocabular['registry']['manage_table_fields']['from_where'];
  s27 = 'Цюрих (Клотен)';
  s28 = 'LSZH';
  s29 = vocabular['registry']['manage_table_fields']['where'];
  s30 = 'Ханчжоу (Сяошань)';
  s31 = 'ZSHC';
  s32 = vocabular['registry']['flight_number'];
  s33 = 'SBI847';
  s34 = vocabular['myPhrases']['regNumPlane'];
  s35 = 'RA10254';
  s36 = vocabular['myPhrases']['dateOut'];
  s37 = '14.04.2020';//??
  s38 = vocabular['myPhrases']['dateIn'];
  s39 = '15.04.2020';//??
  s40 = vocabular['form_n']['purpose_flight'];
  s41 = vocabular['form_n']['purposeFlight']['none_commercial_flight'];
  s42 = vocabular['myPhrases']['transferCategory'];
  s43 = 'Чартерный пассажирский';
  s44 = vocabular['myPhrases']['containedFiles'];
  s45 = 'Разрешение ФСБ';
  s46 = 'согласование Участков маршрута';
  s47 = vocabular['myPhrases']['fligh'];//Используется
  s48 = vocabular['myPhrases']['landing'];//Используется
  s49 = 'Согласовать выбранные участки';
  s50 = 'Отложить';
  //«Нерегулярный рейс №125»';
// s51 = 'Отложить';//Используется
  s52 = vocabular['myPhrases']['cause'];//Используется
  s53 = 'Нерегулярный рейс'; //Используется
  s54 = vocabular['form_n']['flight_information']; //Используется
  s55 = vocabular['registry']['statement'];
  s56 = '1. B Код ИКАО авиапредприятия *_1';
  s57 = '1. C Страна регистрации *_1';
  s58 = '2. Опознавательный индекс ВС (номер...';
  s59 = vocabular['header']['aircrafts'];
  s60 = '3. А Тип основного ВС *';
  s61 = '3.B Регистр. номер ВС *_1';
  s62 = '3. C Макс. взлетная масса *';
  s63 = '3. C Макс. посад. масса *';
  s64 = '3. D Вес пустого снаряж.';
  s65 = '4 – владелец ВС';
  s66 = '4. A Владелец ВС *_4';
  s67 = '4. B Контактные данные владельца *';
  s68 = '4. B Адрес владельца ВС (Государство и полный адрес) *_1';
  s69 = '5 – цель выполнения перевозки';
  s70 = '6. Категория перевозки *';
  s71 = 'Чартерный пассажирский';
  s72 = 'Коммерческий рейс';
  s73 = '7 – экипаж';
  s74 = '7. ФИО *';
  s75 = '7. Гражданство *';
  s76 = vocabular['form_n']['crew']['add_crew_member'];
  s77 = '8 – пассажиры';
  s78 = 'Фрахтователь (наименование) *';
  s79 = 'Полный адрес и контакты *';
  s80 = 'Принимающая сторона (наименование) *';
  s81 = 'Полный адрес и контакты *';
// s82 = '9 – маршрут';
  s83 = '9. Дата отправления *_6';
  s84 = '9. Аэропорт отправления *_5';
  s85 = vocabular['registry']['flight_num'];
// s86 = '9. Время вылета *';
  s87 = '9. Точка входа в ВП РФ *';
  s88 = '9. Время входа *';
  s89 = '9. Точка выхода из ВП РФ *';
  s90 = '9. Время выхода *';
  s91 = '9. Дата прибытия *_6';
  s92 = '9. Аэропорт назначения *_5';
// s93 = '9. Номер рейса *';
  s94 = vocabular['registry']['boarding_time'];
  s95 = 'Пролет над РФ';
  s96 = 'Посадка в РФ';
  s97 = '10 – Форма оплаты услуг и государственных сборов';
  s98 = '10. Адрес плательщика *';
  s99 = '10. Банк *';
  s100 = '10. Номер счета *';
  s101 = 'Примечание_1';
// s102 = 'прикрепленные файлы';
  s103 = vocabular['form_n']['general']['attach_files'];
  s104 = vocabular['forms']['send'];
  s105 = 'Регулярный рейс';
  s106 = vocabular['form_n']['flight_information'];
  s107 = 'Полное наименование авиапредприятия (OPR/) *';
  s108 = 'Номер рейса *';
  s109 = 'SWR (LX) 2688_1';
  s110 = 'Дата c *';
  s111 = 'Дата до *';
  s112 = vocabular['registry']['flight_days'];
  s113 = vocabular['registry']['road'];
  s114 = vocabular['myPhrases']['airportFlight'];
  s115 = vocabular['myPhrases']['airportLanding'];
  s116 = vocabular['registry']['departure_time'];
// s117 = 'Время посадки *';
  s118 = 'Добавить пункты Stop-over';
  s119 = 'Добавить пункты технических посадок';
  s120 = 'Добавить участки с коммерческими правами';
  s121 = vocabular['form_r']['aircraft'];
  s122 = 'Тип основного ВС *_5';
  s123 = 'Компоновка основного ВС *_1';
  s124 = 'Добавить запасное ВС';
  s125 = vocabular['form_r']['entry_exit_points'];
  s126 = 'Точка входа в ВП РФ *_2';
  s127 = 'Точка выхода в ВП РФ *_2';
  s128 = 'Время входа *_7';
  s129 = 'Время выхода *_7';
  s130 = 'Запасные точки входа в ВП РФ *_2';
  s131 = 'Запасные точки выхода из ВП РФ *_2';
  s132 = 'Примечание_1';
  s133 = 'прикрепленные документы';
  s134 = vocabular['form_r']['general']['attach_files'];
  s136 = 'Пункты посадки с правом «Stop-over»';
  s137 = 'Пункт «Stop-over»_5';
// s138 = 'Время вылета *';
// s139 = 'Время посадки *';
  s140 = 'Пункты технических посадок';
  s141 = 'Пункт технической посадки_5';
// s142 = 'Время вылета *';
// s143 = 'Время посадки *';
  s144 = 'Участки с коммерческими правами';
  s145 = 'Причина отказа *';
  s146 = 'Разрешение ФСБ';
// s147 = 'Согласовать';
  s148 = vocabular['form_r']['general']['forms_r'];//Используется
  s149 = 'Действителен с';
  s150 = 'Действителен до';
  s151 = 'Дни выполнения';
// s152 = '14.04.2020';//??
  s153 = '27.04.2020';
  s154 = vocabular['myPhrases']['filters'];
  s155 = vocabular['myPhrases']['newFilter'];
  s156 = vocabular['forms']['my_filters'];
  s157 = vocabular['myPhrases']['sortWith'];
  s158 = vocabular['myPhrases']['flightDateTime'];
  s159 = vocabular['myPhrases']['showArh'];
  s160 = vocabular['myPhrases']['messageType'];
  s161 = vocabular['registry']['manage_table_fields']['from_where'];
  s162 = vocabular['myPhrases']['flightDateTime'];
  s163 = '00.00.0000 в 00:00';
  s164 = 'Плановое скоррект. время вылета';
  s165 = vocabular['registry']['manage_table_fields']['where'];
  s166 = 'КВС';
  s167 = 'SID';
  s168 = vocabular['myPhrases']['factFlightDateTime'];
  s169 = vocabular['myPhrases']['apply'];
  s170 = vocabular['registry']['user_profile']['back']; //Используется
  s171 = 'Внуково';
  s172 = 'UUWW';
  s173 = vocabular['registry']['status_panel']['select'];
  s174 = 'Свернуть все'; //Используется
//примерно тут начал Колдашев Д.Ю.
  s175 = vocabular['myPhrases']['appName'];
  s176 = vocabular['auth']['login'];
  //s177 = 'Пароль *';
  s178 = vocabular['auth']['register_page']['confirmation'];
  s179 = vocabular['auth']['register_page']['surname'];
  s180 = vocabular['auth']['register_page']['name'];
  s181 = vocabular['auth']['register_page']['lastname'];
  s182 = vocabular['myPhrases']['acceptRules'];
// s183 = 'Войти';
  s184 = vocabular['auth']['login_page']['restore_access'];
// s185 = 'Информация о ';
// s186 = 'Пользовательском соглашении';
  s187 = vocabular['auth']['register'];
  s188 = vocabular['myPhrases']['accept'];
  s189 = vocabular['auth']['register_page']['phone'];
  s190 = vocabular['myPhrases']['ICAOcode'];
  s191 = vocabular['header']['settings'];
// s192 = 'Запросы';
  String headerValue = s250;
  s193 = vocabular['header']['exit'];
  s194 = vocabular['header']['groups'];
  s195 = vocabular['myPhrases']['users'];
  s196 = vocabular['myPhrases']['userPoints'];
  s197 = vocabular['myPhrases']['myTemplates'];
  s198 = vocabular['myPhrases']['appSettings'];
  s199 = vocabular['header']['help'];
  s200 = vocabular['myPhrases']['about'];
  s201 = vocabular['notification']['delete_everything'];
  s202 = vocabular['myPhrases']['openReceipt'];
  s203 = vocabular['myPhrases']['notification'];
  s204 = vocabular['header']['profile_and_settings'];
  s205 = vocabular['header']['profile'];
  s206 = vocabular['header']['roles'];
  s207 = vocabular['registry']['user_profile']['personal_data'];
  s208 = vocabular['registry']['user_profile']['update_data'];
  s209 = 'Изменение пароля';
  s210 = 'Введенные пароли не совпадают';
  s211 = 'Изменить пароль';
  s212 = 'Выйти из аккаунта';
  s213 = vocabular['myPhrases']['moreInfo'];
  s214 = vocabular['myPhrases']['general'];
  s215 = vocabular['myPhrases']['language'];
  s216 = 'Доступ по телефону';
  s217 = vocabular['myPhrases']['other'];
  s218 = 'Единицы измерения';
  s219 = 'Единицы измерения температуры';
  s220 = 'Единицы измерения давления';
  s221 = 'Единицы измерения стоимости топлива';
  s222 = 'Единицы измерения вертик. скор. полета';
  s223 = 'Единицы измерения гориз. скор. полета';
  s224 = 'Формат даты';
  s225 = 'Отображение координат';
  s226 = 'Единицы измерения расстояния';
  s227 = 'Единицы измерения высоты';
  s228 = vocabular['myPhrases']['routTimeOutType'];
  s229 = 'Сгенер. список однораз. паролей';
  s230 = 'Исп. одноразовые пароли';
  s231 = vocabular['myPhrases']['showUTC'];
  s232 = 'Доступ для Нафани';
  s233 = 'Мин. высота';
  s234 = 'Макс. высота';
  s235 = 'Автороутинг';
  s236 = 'Настроить уведомления';
  s237 = 'Перейти к подключению SMS';
  s238 = 'Код отправки';
  s239 = 'Идентификатор отправки';
  s240 = 'SMS-уведомления';
  s241 = vocabular['myPhrases']['emailNotif'];
  s242 = vocabular['myPhrases']['themeType'];
  s243 = vocabular['registry']['user_role']['pilot'];
  s244 = vocabular['registry']['user_role']['tune'];
  s245 = 'Внешний пилот БВС';
  s246 = 'Эксплуатант';
  s247 = 'Доверенные пользователи';
  s248 = 'Ожидание запроса';
  s249 = vocabular['myPhrases']['addUser'];
  s250 = vocabular['myPhrases']['reestr'];
  s251 = vocabular['header']['forms_r/n'];
  s252 = vocabular['forms']['form'];
  s253 = vocabular['history'];
  s254 = "${vocabular['form_n']['aircraft'][0].toUpperCase()}${vocabular['form_n']['aircraft'].substring(1)}";//aircraft
  s255 = "${vocabular['form_n']['aircraft_reserve'][0].toUpperCase()}${vocabular['form_n']['aircraft_reserve'].substring(1)}";//"${vocabular['form_n']['aircraft_reserve'][0].toUpperCase()}${vocabular['form_n']['aircraft_reserve'].substring(1)}"
  s256 = "${vocabular['form_n']['main_departure_date'][0].toUpperCase()}${vocabular['form_n']['main_departure_date'].substring(1)}";//main_departure_date
  s257 = vocabular['form_n']['main_departure_date_obj']['repetitions'];
  s258 = vocabular['form_n']['flight_crew'];
  s259 = vocabular['form_n']['cargo'];
  s260 = vocabular['myPhrases']['payer'];
// s260 = 'ЛИЦО ОПЛАЧИВАЮЩЕЕ АЭРОНАВИГАЦИОННЫЕ СБОРЫ';
  s261 = "${vocabular['form_n']['comment'][0].toUpperCase()}${vocabular['form_n']['comment'].substring(1)}";//"${vocabular['form_n']['comment'][0].toUpperCase()}${vocabular['form_n']['comment'].substring(1)}"
  s262 = vocabular['myPhrases']['hintAviacompanyNameOrICAO'];
  s263 = vocabular['myPhrases']['stateOfRegistry'];
  s264 = vocabular['form_n']['general']['add_document'];
  s265 = vocabular['myPhrases']['notes'];
}




//переменные для настройки пользователя
String  regEmail = '', password = '', passwordR = '', familia =' ', name =' ', fatherName = '', regPhone = '', reciveMessage = '', accessToken = '', tokenType = '', expires = '', ikaoReg = '', userId = '';
//дополнительные переменные для настройки пользователя
String passwordOld = '', dopInfo = '';
bool passFieldVisible = true, lockField = true, isPilot = false, isExPilot = false, isExploer = false;

//константы настройки программы
String language = 'en', sendCode = '', senId = '', delayReason = 'Не выбрана', tollUnit = 'Метры', distanceUnit = 'Километры', coordinatUnit = 'ГГММ N/S ГГГMM E/W', dateFormat = 'ДД/ММ/ГГГГ', speedHorisontUnit = 'км/ч', speedVerticalUnit = 'м/с', costUnit = 'Р/литр', presureUnit = 'мм.рт.ст.', temperatureUnit = 'Градусы Цельсия';
int minAllitude = 0, maxAllitude = 10000;
bool darkTheme = true, emailNotif = true, smsNotif = true, autorouting = true, nafanya = true, oneTimePassword = true, showUTC = false;
List <String> languages = ['en','ru'], delayReasons = ['Не выбрана', 'Запрос информации', 'Отмена'], tollUnits = ['Метры', 'Футы', 'Километры'], distanceUnits = ['Километры','Мили'], coordinatUnits = ['ГГММ N/S ГГГMM E/W'], dateFormats= ['ДД/ММ/ГГГГ', 'ГГГГ/ММ/ДД','ММ/ДД/ГГГГ'], speedHorisontUnits = ['км/ч', 'м/с', 'фут/мин.'], speedVerticalUnits = ['км/ч', 'м/с', 'фут/мин.'], costUnits = ['Р/литр', 'Доллар/гал', 'Евро/тонна'], presureUnits = ['мм.рт.ст.', 'Па', 'Атмосферы'], temperatureUnits = ['Градусы Цельсия','Градусы Фаренгейта','Градусы Кельвина'];

//для вебвью
String Url = 'https://lgototvet.koldashev.ru/lgototvet.html';
bool menuShow = false;
bool showRegistryType = true;

